# Generated by Django 2.1.2 on 2018-11-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=100)),
                ('tipoSolicitud', models.CharField(max_length=100)),
                ('motivo', models.CharField(max_length=10000)),
                ('gps', models.CharField(max_length=300)),
            ],
        ),
    ]
